"use strict";
var escola;
(function (escola) {
    const campoNome = document.getElementById("campoNome");
    const campoAno = document.getElementById("campoAnoNasc");
    const campoCpf = document.getElementById("campoCpf");
    const campoEndereco = document.getElementById("campoEndereco");
    const campoTelefone = document.getElementById("campoTelefone");
    const campoMatricula = document.getElementById("campoMatricula");
    const campoCurso = document.getElementById("campoCurso");
    const campoNota1 = document.getElementById("campoNota1");
    const campoNota2 = document.getElementById("campoNota2");
    const campoNota3 = document.getElementById("campoNota3");
    const campoNota4 = document.getElementById("campoNota4");
    const btnCadastroAluno = document.getElementById("CadastroAluno");
    const btnCalcularMedia = document.getElementById("CalcularMedia");
    let aluno;
    btnCadastroAluno.addEventListener("click", () => {
        aluno = new escola.Aluno();
        aluno.nome = campoNome.value;
        aluno.anoNasc = parseInt(campoAno.value);
        aluno.cpf = campoCpf.value;
        aluno.endereco = campoEndereco.value;
        aluno.telefone = campoTelefone.value;
        aluno.matricula = parseInt(campoMatricula.value);
        aluno.curso = campoCurso.value;
        aluno.nota1 = parseFloat(campoNota1.value) || 0;
        aluno.nota2 = parseFloat(campoNota2.value) || 0;
        aluno.nota3 = parseFloat(campoNota3.value) || 0;
        aluno.nota4 = parseFloat(campoNota4.value) || 0;
        document.getElementById("nome").textContent = aluno.nome;
        document.getElementById("idade").textContent = aluno.calcularIdade(2025).toString();
        document.getElementById("AnoNAsc").textContent = aluno.anoNasc.toString();
        document.getElementById("cpf").textContent = aluno.cpf;
        document.getElementById("endereco").textContent = aluno.endereco;
        document.getElementById("telefone").textContent = aluno.telefone;
        document.getElementById("matricula").textContent = aluno.matricula.toString();
        document.getElementById("curso").textContent = aluno.curso;
    });
    btnCalcularMedia.addEventListener("click", () => {
        const media = aluno.calcularMedia();
        document.getElementById("Media").textContent = media.toFixed(2);
    });
})(escola || (escola = {}));
